documents_index:
    path:     /
    defaults: { _controller: "AlxTestTaskBundle:Documents:index" }
    methods:  GET

documents_new:
    path:     /new
    defaults: { _controller: "AlxTestTaskBundle:Documents:new" }
    methods:  [GET, POST]

documents_edit:
    path:     /{id}/edit
    defaults: { _controller: "AlxTestTaskBundle:Documents:edit" }
    methods:  [GET, PUT]

documents_delete:
    path:     /{id}
    defaults: { _controller: "AlxTestTaskBundle:Documents:delete" }
    methods:  DELETE

attachments_index:
    path:     /{id}/attachments
    defaults: { _controller: "AlxTestTaskBundle:Attachments:index" }
    methods:  GET

attachments_new:
    path:     /{id}/attachments
    defaults: { _controller: "AlxTestTaskBundle:Attachments:new" }
    methods:  POST
