services:
    alx_test_task.twig.form_extension:
        class: Alx\TestTaskBundle\Twig\FormExtension
        public: false
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: twig.extension }
