Alx\TestTaskBundle\Entity\Document:
    type: entity
    table: documents
    repositoryClass: Alx\TestTaskBundle\Repository\DocumentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
    oneToMany:
        attachments:
            targetEntity: Alx\TestTaskBundle\Entity\Attachment
            mappedBy: document
            cascade: [persist, remove]
            orderBy:
                order: ASC
    lifecycleCallbacks: {  }
